// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpftc

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadDummyxdp returns the embedded CollectionSpec for dummyxdp.
func loadDummyxdp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DummyxdpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load dummyxdp: %w", err)
	}

	return spec, err
}

// loadDummyxdpObjects loads dummyxdp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*dummyxdpObjects
//	*dummyxdpPrograms
//	*dummyxdpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDummyxdpObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadDummyxdp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// dummyxdpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dummyxdpSpecs struct {
	dummyxdpProgramSpecs
	dummyxdpMapSpecs
	dummyxdpVariableSpecs
}

// dummyxdpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dummyxdpProgramSpecs struct {
	XdpDummy *ebpf.ProgramSpec `ebpf:"xdp_dummy"`
}

// dummyxdpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dummyxdpMapSpecs struct {
}

// dummyxdpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dummyxdpVariableSpecs struct {
}

// dummyxdpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDummyxdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type dummyxdpObjects struct {
	dummyxdpPrograms
	dummyxdpMaps
	dummyxdpVariables
}

func (o *dummyxdpObjects) Close() error {
	return _DummyxdpClose(
		&o.dummyxdpPrograms,
		&o.dummyxdpMaps,
	)
}

// dummyxdpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDummyxdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type dummyxdpMaps struct {
}

func (m *dummyxdpMaps) Close() error {
	return _DummyxdpClose()
}

// dummyxdpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDummyxdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type dummyxdpVariables struct {
}

// dummyxdpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDummyxdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type dummyxdpPrograms struct {
	XdpDummy *ebpf.Program `ebpf:"xdp_dummy"`
}

func (p *dummyxdpPrograms) Close() error {
	return _DummyxdpClose(
		p.XdpDummy,
	)
}

func _DummyxdpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dummyxdp_bpfeb.o
var _DummyxdpBytes []byte
