// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpftc

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type simredirectBpfDevmapVal struct {
	_       structs.HostLayout
	Ifindex uint32
	BpfProg struct {
		_  structs.HostLayout
		Fd int32
	}
}

type simredirectMacKey struct {
	_   structs.HostLayout
	Mac [6]uint8
}

// loadSimredirect returns the embedded CollectionSpec for simredirect.
func loadSimredirect() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SimredirectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load simredirect: %w", err)
	}

	return spec, err
}

// loadSimredirectObjects loads simredirect and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*simredirectObjects
//	*simredirectPrograms
//	*simredirectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSimredirectObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSimredirect()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// simredirectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type simredirectSpecs struct {
	simredirectProgramSpecs
	simredirectMapSpecs
	simredirectVariableSpecs
}

// simredirectProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type simredirectProgramSpecs struct {
	SimRedirectToDst *ebpf.ProgramSpec `ebpf:"sim_redirect_to_dst"`
}

// simredirectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type simredirectMapSpecs struct {
	MacTable *ebpf.MapSpec `ebpf:"mac_table"`
	TxPorts  *ebpf.MapSpec `ebpf:"tx_ports"`
}

// simredirectVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type simredirectVariableSpecs struct {
}

// simredirectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSimredirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type simredirectObjects struct {
	simredirectPrograms
	simredirectMaps
	simredirectVariables
}

func (o *simredirectObjects) Close() error {
	return _SimredirectClose(
		&o.simredirectPrograms,
		&o.simredirectMaps,
	)
}

// simredirectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSimredirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type simredirectMaps struct {
	MacTable *ebpf.Map `ebpf:"mac_table"`
	TxPorts  *ebpf.Map `ebpf:"tx_ports"`
}

func (m *simredirectMaps) Close() error {
	return _SimredirectClose(
		m.MacTable,
		m.TxPorts,
	)
}

// simredirectVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSimredirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type simredirectVariables struct {
}

// simredirectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSimredirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type simredirectPrograms struct {
	SimRedirectToDst *ebpf.Program `ebpf:"sim_redirect_to_dst"`
}

func (p *simredirectPrograms) Close() error {
	return _SimredirectClose(
		p.SimRedirectToDst,
	)
}

func _SimredirectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed simredirect_bpfel.o
var _SimredirectBytes []byte
