// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpftc

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type srcredirectBpfDevmapVal struct {
	_       structs.HostLayout
	Ifindex uint32
	BpfProg struct {
		_  structs.HostLayout
		Fd int32
	}
}

// loadSrcredirect returns the embedded CollectionSpec for srcredirect.
func loadSrcredirect() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SrcredirectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load srcredirect: %w", err)
	}

	return spec, err
}

// loadSrcredirectObjects loads srcredirect and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*srcredirectObjects
//	*srcredirectPrograms
//	*srcredirectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSrcredirectObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSrcredirect()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// srcredirectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type srcredirectSpecs struct {
	srcredirectProgramSpecs
	srcredirectMapSpecs
	srcredirectVariableSpecs
}

// srcredirectProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type srcredirectProgramSpecs struct {
	SrcRedirectToSim *ebpf.ProgramSpec `ebpf:"src_redirect_to_sim"`
}

// srcredirectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type srcredirectMapSpecs struct {
	SimConfigMap      *ebpf.MapSpec `ebpf:"sim_config_map"`
	XdpSrcRedirectMap *ebpf.MapSpec `ebpf:"xdp_src_redirect_map"`
}

// srcredirectVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type srcredirectVariableSpecs struct {
}

// srcredirectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSrcredirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type srcredirectObjects struct {
	srcredirectPrograms
	srcredirectMaps
	srcredirectVariables
}

func (o *srcredirectObjects) Close() error {
	return _SrcredirectClose(
		&o.srcredirectPrograms,
		&o.srcredirectMaps,
	)
}

// srcredirectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSrcredirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type srcredirectMaps struct {
	SimConfigMap      *ebpf.Map `ebpf:"sim_config_map"`
	XdpSrcRedirectMap *ebpf.Map `ebpf:"xdp_src_redirect_map"`
}

func (m *srcredirectMaps) Close() error {
	return _SrcredirectClose(
		m.SimConfigMap,
		m.XdpSrcRedirectMap,
	)
}

// srcredirectVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSrcredirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type srcredirectVariables struct {
}

// srcredirectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSrcredirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type srcredirectPrograms struct {
	SrcRedirectToSim *ebpf.Program `ebpf:"src_redirect_to_sim"`
}

func (p *srcredirectPrograms) Close() error {
	return _SrcredirectClose(
		p.SrcRedirectToSim,
	)
}

func _SrcredirectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed srcredirect_bpfeb.o
var _SrcredirectBytes []byte
