// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpftc

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTcpcap returns the embedded CollectionSpec for tcpcap.
func loadTcpcap() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpcapBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpcap: %w", err)
	}

	return spec, err
}

// loadTcpcapObjects loads tcpcap and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpcapObjects
//	*tcpcapPrograms
//	*tcpcapMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpcapObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcpcap()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpcapSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpcapSpecs struct {
	tcpcapProgramSpecs
	tcpcapMapSpecs
	tcpcapVariableSpecs
}

// tcpcapProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpcapProgramSpecs struct {
	TcPacketCapture *ebpf.ProgramSpec `ebpf:"tc_packet_capture"`
}

// tcpcapMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpcapMapSpecs struct {
	PacketCount *ebpf.MapSpec `ebpf:"packet_count"`
}

// tcpcapVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpcapVariableSpecs struct {
}

// tcpcapObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpcapObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpcapObjects struct {
	tcpcapPrograms
	tcpcapMaps
	tcpcapVariables
}

func (o *tcpcapObjects) Close() error {
	return _TcpcapClose(
		&o.tcpcapPrograms,
		&o.tcpcapMaps,
	)
}

// tcpcapMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpcapObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpcapMaps struct {
	PacketCount *ebpf.Map `ebpf:"packet_count"`
}

func (m *tcpcapMaps) Close() error {
	return _TcpcapClose(
		m.PacketCount,
	)
}

// tcpcapVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcpcapObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpcapVariables struct {
}

// tcpcapPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpcapObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpcapPrograms struct {
	TcPacketCapture *ebpf.Program `ebpf:"tc_packet_capture"`
}

func (p *tcpcapPrograms) Close() error {
	return _TcpcapClose(
		p.TcPacketCapture,
	)
}

func _TcpcapClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpcap_bpfel.o
var _TcpcapBytes []byte
